name: CI Mes Dates

on:
  push:
    branches:
      - '**'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Liste des fichiers
        run: ls -R

      - name: Mise en place du code (Checkout)
        uses: actions/checkout@v4

      - name: Liste des fichiers après checkout
        run: ls -R